image: Visual Studio 2015
version: 1.0.{build}

environment:
  matrix:
    - PLATFORM: x86
    - PLATFORM: x86
    - BUILDTYPE: Release
    - BUILDTYPE: Debug

clone_folder: c:\projects\leveldb
init:
- if "%PLATFORM%"=="x64" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
- if "%PLATFORM%"=="x86" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
build_script:
- cmd: >-
    cd c:\projects\leveldb

    mkdir build

    cd build

    cmake --version

    cmake -G "NMake Makefiles" .. -DCMAKE_INSTALL_PREFIX=../../install/appveyor -DCMAKE_BUILD_TYPE=%BUILDTYPE% -DBOOST_ROOT=C:\Libraries\boost_1_62_0

    nmake install
test_script:
- cmd: nmake test