version: 1.0.{build}
clone_folder: c:\projects\leveldb
init:
- cmd: '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
build_script:
- cmd: >-
    dir C:\Libraries\boost_1_60_0\lib64-msvc-14.0
	
    cd c:\projects\leveldb
	
    mkdir build
	
    cd build
	
    cmake --version
	
    cmake -G "NMake Makefiles" .. -DCMAKE_INSTALL_PREFIX=../../install/appveyor -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=C:\Libraries\boost_1_60_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_60_0\lib64-msvc-14.0

    nmake install
test_script:
- cmd: nmake test