version: 1.0.{build}
clone_folder: c:\projects\leveldb
build_script:
- cmd: >-
    cd c:\projects\leveldb

    mkdir build

    cd build

    cmake -G "NMake Makefiles" ../.. -DCMAKE_INSTALL_PREFIX=../../install/appveyor -DCMAKE_BUILD_TYPE=Debug

    nmake install
test_script:
- cmd: nmake test